### ISSUE TITLE
blockhosts.py not working because it cannot process ip address

### ISSUE THREAD

**Issue by dreamcarrior** [avinash311/blockhosts#1]
I installed in Ubuntu 20.04 with the tarball version. After configuration, I had the following error.

`sudo blockhosts.py 
ERROR:  Failed to load blockfile, unexpected error
Traceback (most recent call last):
  File "/usr/bin/blockhosts.py", line 2175, in <module>
    sys.exit(main())
  File "/usr/bin/blockhosts.py", line 2085, in main
    dh.load_hosts_blockfile(prev_logoffsets)
  File "/usr/bin/blockhosts.py", line 1431, in load_hosts_blockfile
    state = self._process_state_2(fp, logoffsets, line)
  File "/usr/bin/blockhosts.py", line 1487, in _process_state_2
    name, value = line.split(" : ", 1)`

I looked into the blockhosts.py and modified the line 1487 to 
`name, value = line.split(":", 1)`

then everything works.

Thanks!

**Comment by avinash311** [comment]
This seems odd - using just `:` will cause problems since IPv6 addresses use that character.
blockhosts therefore adds a space around it to the lines it creates.

Line 1598 explains why:
```
             # Using " : " as markers, not just : since : is part of IPv6 address
```
